# Uncomment the next line to define a global platform for your project
# platform :ios, '11.2'
source 'https://github.com/MapQuest/podspecs-ios.git'

source 'https://github.com/CocoaPods/Specs.git'
target 'UverBus' do
  pod 'MapboxNavigation', '~> 0.27.0'
  pod 'Mapbox-iOS-SDK', '~> 4.7'
  pod 'Firebase'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UverBus

  target 'UverBusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UverBusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
